### ISSUE TITLE
backup show completed but medusa status show incomplete.

### ISSUE THREAD

**Issue by lax-m** [thelastpickle/cassandra-medusa#59]
Hello,
I used pssh to take backup on my 2 node cluster using 
` pssh -H "host1 host2" medusa backcup --backup-name=22012020`

`[2020-01-22 09:35:21,338] INFO: Updating backup index
[2020-01-22 09:35:22,161] INFO: Backup done
[2020-01-22 09:35:22,161] INFO: - Started: 2020-01-22 09:34:50
                        - Started extracting data: 2020-01-22 09:34:52
                        - Finished: 2020-01-22 09:35:22
[2020-01-22 09:35:22,161] INFO: - Real duration: 0:00:29.203785 (excludes time waiting for other nodes)
[2020-01-22 09:35:22,162] INFO: - 261 files, 1.23 MB
[2020-01-22 09:35:22,162] INFO: - 261 files copied from host
`
Upon executing ` medusa status --backup-name=22012020 `
It shows incomplete. There is apprx no data in this test cluster. 

`22012020 [Incomplete!]
- Started: 2020-01-22 09:34:53, Finished: never
- 2 nodes completed, 0 nodes incomplete, 1 nodes missing
- Missing nodes:
    host2
- 531 files, 2.45 MB`

**Comment by adejanovski** [comment]
Hi, 

Which storage backend are you using? Is it `local`?
If so, then you need to use a shared storage for the backup folder, which all nodes have to use, otherwise they cannot see each other backups.

**Comment by lax-m** [comment]
using s3_ap_south. I see backups happening. Folders along with data and metadata are being created.

**Comment by adejanovski** [comment]
Could you paste the output of `medusa verify --backup-name=22012020` running on host2 here?
Which files do you see in the bucket under `host1/22012020/meta` and `host2/22012020/meta`?
could you run the backups individually, without pssh, so that we can check the problem is only related to medusa?

**Comment by lax-m** [comment]
[](url)
<img width="585" alt="Screenshot 2020-01-22 at 5 03 11 PM" src="https://user-images.githubusercontent.com/56817161/72890979-30d64380-3d39-11ea-8bad-61c3adcf75cc.png">

these are the files in both hosts 22012020/meta folder

**Comment by adejanovski** [comment]
is the name of host2 the same in both:
- the folder name in the bucket
- and name contained in tokenmap.json

or is it different?

**Comment by lax-m** [comment]
- qa4-scylla-backup(s3 bucket)
      -  host1
            - 22012020
            - data
      - host2
            - 22012020
            - data
      - index

**Comment by adejanovski** [comment]
Hi,

the tokenmap.json files should all contain the same data, and have both host names each. This files describes the whole cluster.
Could you share the tokenmap files after obfuscating the hostnames, but making sure they match the names from the bucket's directories?
Also, I see you're using ScyllaDB based on the bucket name. We yet have to confirm this but there could be some differences that confuse Medusa.

**Comment by lax-m** [comment]
The tokenmap.json contains the same data for both the hosts with their respective hostnames. 
<img width="837" alt="Screenshot 2020-01-23 at 1 31 38 PM" src="https://user-images.githubusercontent.com/56817161/72966329-b400a380-3de4-11ea-9bf0-88d279bdfb8b.png">

Yeah i am using this for scylladb

**Comment by adejanovski** [comment]
I'm sorry I'd need more informations to pursue the investigation. Could you compress the content of the bucket and send it to me at alex[at]thelastpickle.com?
I need to check the index and the meta files to understand why Medusa can't match the nodes to the actual backups correctly.
If you could leave them unaltered, it would be a plus, but I understand that could be problematic.

**Comment by adejanovski** [comment]
Hi @lax-m,

any chance you made some progress on this issue?

**Comment by alvaropalmeirao** [comment]
Hi,

I have the same problem as @lax-m. Do you need any info from my use case to pursue this problem?

**Comment by adejanovski** [comment]
Thanks @alvaropalmeirao,
that's gonna be very helpful.
Could you compare the output of `medusa list-backups` from all nodes and see if they match?
Could you post here the output of `medusa verify` for the backup that is reported as incomplete?
For the node that's supposed to be incomplete, you'll need to check in the bucket that said backup `meta`  files are all present. they're located under `<fqdn>/<backup_name>/meta/`. You should have there a `tokenmap.json`, `manifest.json` and `schema.cql` (plus a `differential` or `incremental`  file if you've used differential backups).

Also, under `index/backup_index/<backup_name>` you should have a `started_...` and a `finished_...` file for each host : 
![S3 Management Console (3)](https://user-images.githubusercontent.com/5096002/74028644-265bb100-49ab-11ea-92af-1e62627c79ef.png)

Do you see a `finished_....` file for all hosts, and especially one for the host that is reporting an incomplete backup?

**Comment by alvaropalmeirao** [comment]
Hi,

I'm using ScyllaDB as @lax-m. Regarding your questions (ansible output):

```Could you compare the output of medusa list-backups from all nodes and see if they match?```
```
scylladb-general-3db72f7f00 | CHANGED | rc=0 >>
2020020714 (started: 2020-02-07 14:17:41, finished: Incomplete [6 of 6 nodes finished])

Incomplete backups found. You can run "medusa status --backup-name <name>" for more details

scylladb-general-54d8c0fd9c | CHANGED | rc=0 >>
2020020714 (started: 2020-02-07 14:17:41, finished: Incomplete [6 of 6 nodes finished])

Incomplete backups found. You can run "medusa status --backup-name <name>" for more details

scylladb-general-97413d4ad4 | CHANGED | rc=0 >>
2020020714 (started: 2020-02-07 14:17:41, finished: Incomplete [6 of 6 nodes finished])

Incomplete backups found. You can run "medusa status --backup-name <name>" for more details

scylladb-general-c2a061504a | CHANGED | rc=0 >>
2020020714 (started: 2020-02-07 14:17:41, finished: Incomplete [6 of 6 nodes finished])

Incomplete backups found. You can run "medusa status --backup-name <name>" for more details

scylladb-general-d8d817290e | CHANGED | rc=0 >>
2020020714 (started: 2020-02-07 14:17:41, finished: Incomplete [6 of 6 nodes finished])

Incomplete backups found. You can run "medusa status --backup-name <name>" for more details

scylladb-general-02c6ca4291 | CHANGED | rc=0 >>
2020020714 (started: 2020-02-07 14:17:41, finished: Incomplete [6 of 6 nodes finished])

Incomplete backups found. You can run "medusa status --backup-name <name>" for more details
```

```Could you post here the output of medusa verify for the backup that is reported as incomplete?```
[Medusa_Verify.log](https://github.com/thelastpickle/cassandra-medusa/files/4171378/Medusa_Verify.log)

```
# medusa status --backup-name=2020020714
2020020714 [Incomplete!]
- Started: 2020-02-07 14:34:19, Finished: never
- 6 nodes completed, 0 nodes incomplete, 5 nodes missing
- Missing nodes:
    scylladb-general-02c6ca4291
    scylladb-general-97413d4ad4
    scylladb-general-c2a061504a
    scylladb-general-d8d817290e
    scylladb-general-54d8c0fd9c
- 2376 files, 8.42 MB
```
As you can see from the above output I have 0 nodes incomplete and 5 missing. On other hosts the message is the same (6 nodes completed, 0 nodes incomplete, 5 nodes missing) and the missing nodes are the same. So, i dont have incomplete nodes, only missing nodes.

On the bucket, under <fqdn>/<backup_name>/meta/ of each hostname i have those 4 files and under ```index/backup_index/<backup_name>``` i have a started_ and a finished_ file for each host as well.

Do you need more info?

**Comment by adejanovski** [comment]
Thanks @alvaropalmeirao,

could you share the content of one of the tokenmap.json files from the meta folder?

Also, the output of `medusa verify` is claiming that many files don't exist, for example : 
```
scylladb-general-d8d817290e/data/system_schema/view_virtual_columns-08843b6345dc3be29798a0418295cfaa/mc-2-big-Scylla.db
```

Do you see this file in the bucket?
Do you have one folder per host (named with the proper hostname, for example `scylladb-general-02c6ca4291`) at the root of the bucket?

**Comment by alvaropalmeirao** [comment]
Hi,

File attached. I've changed the FQDN of my machines to ```scylladb-general-54d8c0fd9c.<consul_fqdn>``` for security purposes.

Regarding the output that claims that the file don't exist... The file exists in the bucket! 
I've used the prefix option so that in the root of the bucket i have the cluster name and inside of it i have 6 folders, one for each host of the cluster, e.g:
```
-bucket_root
---> scylladb-general (prefix)
---------> host 1
---------------> data
---------------> 2020020714
---------> host 2
---------------> data
---------------> 2020020714
---------> host 3
---------------> data
---------------> 2020020714
---------> host 4
---------------> data
---------------> 2020020714
---------> host 5
---------------> data
---------------> 2020020714
---------> host 6
---------------> data
---------------> 2020020714
```

If you need more info please feel free.

**Comment by adejanovski** [comment]
oh ok, prefixes are currently broken. The fix is waiting for a review in #71 .
So I guess you either need to retry without a prefix, or wait until the fix is merged and released.

**Comment by alvaropalmeirao** [comment]
I retried without prefix and the problem persists. But this time i can read the manifest but the output that i have is different (i have replaced FQDN):
```
# medusa verify --backup-name 2020020716
Validating 2020020716 ...
- Completion: Not complete!
  - [scylladb-general-97413d4ad4.<consul_fqdn>] Backup missing
  - [scylladb-general-c2a061504a.<consul_fqdn>] Backup missing
  - [scylladb-general-02c6ca4291.<consul_fqdn>] Backup missing
  - [scylladb-general-d8d817290e.<consul_fqdn>] Backup missing
  - [scylladb-general-54d8c0fd9c.<consul_fqdn>] Backup missing
- Manifest validated: OK!!
```
A funny thing that i noticed (and i've writen above) is that in tokenmap.json on each host folder has the 1st hostname (itself) without FQDN and the following hostnames have FQDN. Example:
S3 File: ```scylladb-general-54d8c0fd9c/<backup_name>/meta/tokenmap.json```
```
{
"scylladb-general-54d8c0fd9c": {
"tokens": [
1108540824836743200,
-8202936612176019000,
-2846554974582190000,
-4252052544333021000,
.....
],
"is_up": true
},
"scylladb-general-97413d4ad4.<consul_fqdn>": {
"tokens": [
1318523870119035000,
-2497169926705479700,
...
],
"is_up": true
},
"scylladb-general-d8d817290e.<consul_fqdn>": {
tokens": [
5390246029656867000,
-3459188782062960600,
...
],
"is_up": true
},
"scylladb-general-c2a061504a.<consul_fqdn>": {
"tokens": [
-6969039803518657000,
578152159362527400,
...
],
"is_up": true
},
"scylladb-general-02c6ca4291.<consul_fqdn>": {
"tokens": [
7765203865960346000,
-3385095405746450400,
...
```
and so on to the 6th node.

S3 File: ```scylladb-general-97413d4ad4/<backup_name>/meta/tokenmap.json```
```
{
"scylladb-general-d8d817290e.<consul_fqdn>": {
"is_up": true,
"tokens": [
5390246029656867000,
-3459188782062960600,
...
]
},
"scylladb-general-97413d4ad4": {
"is_up": true,
"tokens": [
1318523870119035000,
-2497169926705479700,
...
]
},
"scylladb-general-02c6ca4291.<consul_fqdn>": {
"is_up": true,
"tokens": [
7765203865960346000,
-3385095405746450400,
...
]
},
"scylladb-general-c2a061504a.<consul_fqdn>": {
"is_up": true,
"tokens": [
-6969039803518657000,
... 
```
and so on to the 6th node.

And all of this happens on the others tokenmap.json files on the other host folders.
Could this be a problem?

**Comment by alvaropalmeirao** [comment]
New info: 
If i go to the file ```index/backup_index/2020020717/tokenmap_scylladb-general-02c6ca4291.json and remove the FQDN of all hosts it fixes the problem:

```
# medusa report-last-backup
[2020-02-07 17:43:38,779] INFO: Monitoring provider is noop
[2020-02-07 17:43:38,999] INFO: Latest node backup finished 1905 seconds ago
[2020-02-07 17:43:39,082] INFO: Latest complete backup:
[2020-02-07 17:43:39,082] INFO: - Name: 2020020717
[2020-02-07 17:43:39,082] INFO: - Finished: 1903 seconds ago
[2020-02-07 17:43:39,114] INFO: Latest backup:
[2020-02-07 17:43:39,114] INFO: - Name: 2020020717
[2020-02-07 17:43:39,138] INFO: - Finished: True
[2020-02-07 17:43:39,139] INFO: - Details - Node counts
[2020-02-07 17:43:39,139] INFO: - Complete backup: 6 nodes have completed the backup
[2020-02-07 17:43:39,519] INFO: - Total size: 8.42 MiB
[2020-02-07 17:43:39,522] INFO: - Total files: 2376
```

```
# medusa verify --backup-name=2020020717
Validating 2020020717 ...
- Completion: OK!
- Manifest validated: OK!!
```

```
# medusa status --backup-name 2020020717
2020020717
- Started: 2020-02-07 17:11:16, Finished: 2020-02-07 17:11:56
- 6 nodes completed, 0 nodes incomplete, 0 nodes missing
- 2376 files, 8.42 MB
```

Why this happens?

**Comment by adejanovski** [comment]
Apparently ScyllaDB is picking different forms of hostnames for the local node and remote ones 🤔 
I guess we could work around this by resolving the names we're getting from the tokenmap to their FQDN.
Unless you've edited the outputs, it seems like Medusa is picking the hostnames without the consul fqdn all the time, so it's only the hostnames from the tokenmap that need to be cleaned up. 

Could you check that `socket.getfqdn("scylladb-general-02c6ca4291.<consul_fqdn>")` resolves to `scylladb-general-02c6ca4291` on your machines (using python3) ?

**Comment by alvaropalmeirao** [comment]
The only outputs that i've edited are the ones that i hide the Consul FQDN.

```
python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> socket.getfqdn("scylladb-general-97413d4ad4.<consul_fqdn>")
'scylladb-general-97413d4ad4'
>>>
```

Do you need anything else from my side? Thanks!

**Comment by adejanovski** [comment]
nice, then I think we can work it out this way.
I'll try to send a PR shortly to fix this and will let you know.

**Comment by alvaropalmeirao** [comment]
Thank you! Much appreciated your effort on this. 
If you need anything please let me know.

**Comment by alvaropalmeirao** [comment]
Hi,

Do you have any news? Thank you.

**Comment by adejanovski** [comment]
I'm working on this right now. Turns out, as usual, that things aren't as simple as they seem.
My fix is breaking integration tests and I need to figure another way to deal with this.
I'll update as soon as I can, but I need to cut out a release in the meantime.

**Comment by alvaropalmeirao** [comment]
Ok, thank you! If you want you can provide me the code that fixes this issue so that I can continue the fix and my tests as well. We're here the help! :) 
Thanks again for the effort! 💪

**Comment by adejanovski** [comment]
This issue was fixed in #163 by introducing a new setting which disables hostname resolving.

**Comment by Lucasafisher** [comment]
I also had this problem but resolve_ip_addresses did not solve the issue. For me the issue was solved by giving the cassandra node running the command the ability to resolve the ip addresses of the other nodes to their hostname. I was noticing that the first node in the list was resolving to its name but the others were just ip address'. Adding entries to the /etc/host file on that cassandra node changed it so all nodes were referred to by their hostnames which solved the issue.
